blank_issues_enabled: false
contact_links:
  - name: "\U0001F4AC FAQ"
    url: https://github.com/CertifaiAI/CertifAI-Knowledge-Base/wiki
    about: "Please check your questions/issues here. Your questions may already have been answered. \U0001F642"